{{- if .Values.gethSetup -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "geth-swap.fullname" . }}-setupcontracts
  labels:
    {{- include "geth-swap.labels" . | nindent 4 }}
spec:
  template:
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
      - name: setup
        image: "{{ .Values.imageSetupContract.repository }}:{{ .Values.imageSetupContract.tag }}"
        imagePullPolicy: {{ .Values.imageSetupContract.pullPolicy }}
        env:
          - name: BACKEND
            value: "http://{{ include "geth-swap.fullname" . }}:8545"
          - name: BZZACCOUNTS
            value: {{ .Values.swap.bzzaccounts | join " " }}
          {{ if .Values.swap.gas }}
          - name: GAS
            value: {{ .Values.swap.gas | quote }}
          {{ end }}
        command:
          - sh
          - -ac
          - >
            set -x;
            while ! curl -m 1 $BACKEND; do sleep 1; done;
            echo connected to geth >&2;
            sleep 2;
            bash deploy.sh
      restartPolicy: Never
{{- end -}}