{{- if and .Values.gatewayProxy.enabled .Values.gatewayProxy.ingress.enabled -}}

{{- $root := . -}}
{{- $fullName := include "bee.fullname" $root -}}

# PER POD INGRESS
{{- range $i, $e := until (int $root.Values.replicaCount) }}
---
{{- if semverCompare ">=1.19-0" $root.Capabilities.KubeVersion.Version }}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: gateway-proxy-{{ $fullName }}-{{ $i }}
  namespace: {{ $root.Release.Namespace }}
  labels:
    {{- include "bee.labels" $root | nindent 4 }}
  {{- with $root.Values.gatewayProxy.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if $root.Values.gatewayProxy.ingress.tls }}
  tls:
  {{- range $root.Values.gatewayProxy.ingress.hosts }}
    - hosts:
      {{- if .domain }}
        - gateway-proxy-{{ $fullName }}-{{ $i }}.{{ .domain }}
      {{- else }}
        - gateway-proxy-{{ $fullName }}-{{ $i }}
      {{- end }}
    {{- if .tlsSecret }}
      secretName: {{ .tlsSecret }}
    {{- end }}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.18-0" $root.Capabilities.KubeVersion.Version }}
  ingressClassName: {{ $root.Values.gatewayProxy.ingress.ingressClassName }}
{{- end }}
  rules:
  {{- range $root.Values.gatewayProxy.ingress.hosts }}
    {{- if .domain }}
    - host: gateway-proxy-{{ $fullName }}-{{ $i }}.{{ .domain }}
    {{- else }}
    - host: gateway-proxy-{{ $fullName }}-{{ $i }}
    {{- end }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
          {{- if semverCompare ">=1.18-0" $root.Capabilities.KubeVersion.Version }}
            pathType: {{ $root.Values.gatewayProxy.ingress.pathType }}
          {{- end }}
            backend:
            {{- if semverCompare ">=1.19-0" $root.Capabilities.KubeVersion.Version }}
              service:
                name: gateway-proxy-{{ $fullName }}-{{ $i }}
                port:
                  name: gateway-proxy
            {{- else }}
              serviceName: gateway-proxy-{{ $fullName }}-{{ $i }}
              servicePort: gateway-proxy
            {{- end }}
        {{- end }}
  {{- end }}
{{- end }}

{{- end -}}
