name: Lint and Test

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v2.1.0
        with:
          command: lint

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        if: steps.lint.outputs.changed == 'true'

      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v2.1.0
        with:
          command: install
